DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS PRODUCTOS;
DROP TABLE IF EXISTS COMPROBANTE;
DROP TABLE IF EXISTS VENTA;

CREATE TABLE CLIENTES(
IDCLIENTE INT NOT NULL AUTO_INCREMENT,
DNI INT NOT NULL,
NOMBRE VARCHAR(200) NOT NULL,
APELLIDO VARCHAR(200) NOT NULL,
FECHANACIMIENTO DATE NOT NULL,
PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE PRODUCTOS(
IDPRODUCTO INT NOT NULL AUTO_INCREMENT,
DESCRIPCION VARCHAR(200) NOT NULL,
PRECIO FLOAT NOT NULL,
STOCK INT NOT NULL,
CODIGO VARCHAR(7) NOT NULL,
PRIMARY KEY (IDPRODUCTO)
);

CREATE TABLE COMPROBANTE(
IDCOMPROBANTE INT NOT NULL AUTO_INCREMENT,
IDVENTA INT NOT NULL,
IDCLIENTE INT NOT NULL,
NOMBREAPELLIDO VARCHAR(200),
IDPRODUCTO INT NOT NULL,
DESCRIPCION VARCHAR(200),
CANTIDAD INT NOT NULL,
FECHA DATE,
TOTAL FLOAT NOT NULL,
PRIMARY KEY (IDCOMPROBANTE)
);

CREATE TABLE VENTA(
IDVENTA INT NOT NULL AUTO_INCREMENT,
IDPRODUCTO INT NOT NULL,
CANTIDAD INT NOT NULL,
PRECIOTOTAL FLOAT NOT NULL,
IDCLIENTE INT NOT NULL,
IDCOMPROBANTE INT NOT NULL,

PRIMARY KEY(IDVENTA)
);